### ISSUE TITLE
Please publish 1.0.0 to npm

### ISSUE THREAD

**Issue by strugee** [hassaku/hubot-suggest#10]
The semantic versioning specification [states][1]:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

However, in hubot-suggest's case, this isn't really accurate. At a certain point a project has been around long enough that it should be considered stable. Any future changes can be made in semver-major releases. (Also consider - especially for a smaller project like hubot-suggest, semi-frequent semver-major changes aren't the end of the world. They just aren't.)

Please publish 1.0.0 to npm to indicate that hubot-suggest is at least a somewhat mature project.

 [1]: http://semver.org/#spec-item-4

**Comment by hassaku** [comment]
Thanks! I did it.

**Comment by strugee** [comment]
:thumbsup: thank you!
